import { Link } from 'react-router-dom';
import { LegalPageLayout } from '../components/LegalPageLayout';
import type { LegalSection } from '../components/LegalPageLayout';
import { company } from '../data/company';
import { contact } from '../data/contact';
import { corporateOfficeLocation } from '../data/mapLocations';

const LAST_UPDATED = '2 October 2026';

const sections: LegalSection[] = [
  {
    id: 'introduction',
    heading: 'Introduction and scope',
    body: (
      <>
        <p>
          {company.legalName} (&ldquo;Divine Vision&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) operates
          this website, its chatbot (&ldquo;Divine Assist&rdquo;), and the customer and channel-partner (broker)
          dashboards reachable from it (together, the &ldquo;Platform&rdquo;). This Privacy Policy explains what
          personal data we collect through the Platform, why, how it is kept, and the rights you have over it.
        </p>
        <p>
          This policy is framed in line with the <strong>Digital Personal Data Protection Act, 2023</strong> (&ldquo;DPDP
          Act&rdquo;) and its rules, the <strong>Information Technology Act, 2000</strong> and the Information Technology
          (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, and
          the disclosure norms expected of a real-estate developer under the{' '}
          <strong>Real Estate (Regulation and Development) Act, 2016</strong> (&ldquo;RERA&rdquo;). Under the DPDP Act,
          Divine Vision is the &ldquo;Data Fiduciary&rdquo; for the personal data you share with us, and you are the
          &ldquo;Data Principal&rdquo;.
        </p>
        <p>
          By using the Platform, booking a plot, signing up as a customer or channel partner, or chatting with Divine
          Assist, you agree to the collection and use of information as described here. If you do not agree, please
          do not use the Platform and contact us using the details under{' '}
          <a href="#grievance">&ldquo;Grievance Officer and contact&rdquo;</a> instead.
        </p>
      </>
    ),
  },
  {
    id: 'data-we-collect',
    heading: 'Personal data we collect',
    body: (
      <>
        <p>We collect only what a given step of the Platform actually needs:</p>
        <ul>
          <li>
            <strong>Account and contact details</strong> — name, email address, phone number and password (stored in
            hashed form; we never see or store your plaintext password) when you sign up as a customer or channel
            partner, or sign in through the chatbot.
          </li>
          <li>
            <strong>Booking application details</strong> — applicant and co-applicant name, date of birth, gender,
            father&rsquo;s/guardian&rsquo;s name, residential status, permanent and correspondence address, and
            PAN/Aadhaar numbers, entered on the booking application form.
          </li>
          <li>
            <strong>KYC documents (sensitive personal data)</strong> — Aadhaar front/back photo or Aadhaar
            QR/offline-XML data, PAN card photo, applicant and co-applicant photographs, signatures, and a cancelled
            cheque, uploaded as part of the booking application. These are collected because RERA and anti-money-
            laundering norms require verified buyer identification before a plot can be locked to you.
          </li>
          <li>
            <strong>Payment information</strong> — the amount, purpose and status of a payment, and identifiers
            returned by our payment gateway (Zoho Payments). We do not collect or store your card, UPI or bank
            account details ourselves — these are handled directly by Zoho Payments, an RBI-regulated payment
            aggregator.
          </li>
          <li>
            <strong>Site-visit requests</strong> — name, phone number and preferred date/time when you book a site
            visit.
          </li>
          <li>
            <strong>Chat conversations</strong> — messages you send to Divine Assist, and, if you choose to report a
            problem with a reply, the message you flagged and your note about it.
          </li>
          <li>
            <strong>Broker/channel-partner details</strong> — in addition to the above, the township you represent,
            leads and site visits you record, and commission records tied to bookings you bring in.
          </li>
          <li>
            <strong>Technical data</strong> — standard web-server logs (IP address, browser type, pages requested,
            timestamps) generated by any website visit, and the limited device information needed to make the
            chatbot and payment flows work.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 'how-we-use-it',
    heading: 'How we use your data',
    body: (
      <ul>
        <li>To create and operate your customer or channel-partner account.</li>
        <li>
          To process a plot booking: lock an inventory unit to you, route your KYC documents for review, generate the
          booking application PDF, and record payments against your payment plan.
        </li>
        <li>
          To verify your identity as required for a real-estate transaction under RERA and applicable
          anti-money-laundering guidance.
        </li>
        <li>To schedule and manage site visits.</li>
        <li>To respond to you through Divine Assist, by phone, email or WhatsApp.</li>
        <li>To calculate and track channel-partner commissions.</li>
        <li>
          To meet our legal and regulatory obligations, including those under RERA, the Income Tax Act, 1961, and
          other applicable law, and to maintain records for the statutory period those laws require.
        </li>
        <li>To keep the Platform secure and to detect and prevent fraud or misuse.</li>
      </ul>
    ),
  },
  {
    id: 'legal-basis',
    heading: 'Legal basis for processing',
    body: (
      <p>
        We process your personal data on the basis of your <strong>consent</strong> (given when you sign up, submit a
        booking application, or start a chat), and, once you have begun a booking, on the basis that the processing is
        <strong> necessary to perform our obligations</strong> to you in connection with that booking. Where the law
        requires us to keep records — for example, RERA- or tax-related records — we continue to process the minimum
        data needed for that specific legal obligation even after any other purpose has ended.
      </p>
    ),
  },
  {
    id: 'storage-security',
    heading: 'How and where your data is stored',
    body: (
      <>
        <p>
          Your account, booking and document data is stored on secure servers and encrypted in transit using HTTPS/TLS.
          KYC documents you upload are sent directly to our backend&rsquo;s document storage and are not retained as
          raw files in your browser once the upload is confirmed.
        </p>
        <h3>What this browser keeps on your own device</h3>
        <p>
          The Platform does not use third-party advertising or analytics cookies. To keep you signed in and let a form
          survive a page refresh, it stores a small amount of data in your browser&rsquo;s own local storage —
          readable only by this site, never sent to any third party except our backend:
        </p>
        <ul>
          <li>Your sign-in session (an access token that expires automatically).</li>
          <li>
            A temporary copy of any document you&rsquo;re mid-way through uploading, cleared once our servers confirm
            receipt, and always cleared when you sign out.
          </li>
          <li>Non-sensitive preferences, like townships you&rsquo;ve saved or a visit you were about to book.</li>
        </ul>
        <p>Signing out from the account menu clears this device-side data for that account.</p>
      </>
    ),
  },
  {
    id: 'sharing',
    heading: 'Who we share data with',
    body: (
      <>
        <p>We do not sell your personal data. We share it only where necessary to run the Platform or meet the law:</p>
        <ul>
          <li>
            <strong>Zoho Payments</strong>, to process a payment you initiate — governed by Zoho&rsquo;s own privacy
            terms for the payment details you enter on their hosted checkout page.
          </li>
          <li>
            <strong>Cloud hosting and infrastructure providers</strong>, who store data on our behalf under contract
            and are not permitted to use it for their own purposes.
          </li>
          <li>
            <strong>RERA authorities, courts, regulators or law-enforcement agencies</strong>, where disclosure is
            required by law or a valid legal process.
          </li>
          <li>
            <strong>The developer/promoter entity of the specific township you book</strong>, to the extent needed to
            process your booking and prepare the Agreement for Sale.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 'retention',
    heading: 'How long we keep it',
    body: (
      <p>
        We keep booking, payment and KYC records for as long as the law requires real-estate transaction records to be
        kept (including the record-keeping periods under RERA and tax law), and for as long as needed to defend or
        bring a legal claim after that. Account data you never convert into a booking is kept only for as long as your
        account stays active, or until you request erasure under{' '}
        <a href="#your-rights">&ldquo;Your rights as a Data Principal&rdquo;</a>.
      </p>
    ),
  },
  {
    id: 'aadhaar',
    heading: 'Aadhaar and other government ID',
    body: (
      <p>
        Where you choose to verify your identity using Aadhaar, we process the minimum data returned by that
        verification (your masked Aadhaar number, name, and the demographic fields on the Aadhaar QR/offline-XML) only
        to pre-fill and confirm your booking application, in line with the Aadhaar Act, 2016 and UIDAI&rsquo;s
        guidelines on offline, consent-based Aadhaar verification. We do not store your full Aadhaar number, and
        Aadhaar-based verification is never a condition for browsing the Platform — it is only used once you choose to
        start a booking.
      </p>
    ),
  },
  {
    id: 'your-rights',
    heading: 'Your rights as a Data Principal',
    body: (
      <>
        <p>Under the DPDP Act, 2023, you have the right to:</p>
        <ul>
          <li>Obtain a summary of the personal data we hold about you and how it has been processed.</li>
          <li>Ask us to correct, complete or update inaccurate or outdated personal data.</li>
          <li>
            Ask us to erase personal data that is no longer necessary for the purpose it was collected for, subject
            to our legal record-keeping obligations described under{' '}
            <a href="#retention">&ldquo;How long we keep it&rdquo;</a>.
          </li>
          <li>Withdraw consent at any time, without affecting anything already done on the basis of that consent.</li>
          <li>Nominate another individual to exercise these rights on your behalf in the event of your death or incapacity.</li>
          <li>Lodge a grievance with us, and, if unresolved, with the Data Protection Board of India.</li>
        </ul>
        <p>
          To exercise any of these, write to the Grievance Officer under{' '}
          <a href="#grievance">&ldquo;Grievance Officer and contact&rdquo;</a>. We will
          acknowledge your request and respond within the time limit prescribed under the DPDP Act and its rules.
        </p>
      </>
    ),
  },
  {
    id: 'minors',
    heading: 'Children’s data',
    body: (
      <p>
        The Platform is not directed at children. Booking a plot is a legal transaction under the Indian Contract Act,
        1872 and requires you to be at least 18 years old and otherwise competent to contract. We do not knowingly
        collect personal data from anyone under 18; if we learn that we have, we will delete it.
      </p>
    ),
  },
  {
    id: 'changes',
    heading: 'Changes to this policy',
    body: (
      <p>
        We may update this policy as our services, or the law, change. The &ldquo;Last updated&rdquo; date at the top
        of this page always reflects the current version. Material changes affecting how we handle your existing data
        will be notified to registered users by email or an in-app notice before they take effect.
      </p>
    ),
  },
  {
    id: 'grievance',
    heading: 'Grievance Officer and contact',
    body: (
      <>
        <p>
          In accordance with the DPDP Act, 2023 and the Information Technology Act, 2000, grievances or requests
          relating to your personal data can be sent to our Grievance Officer:
        </p>
        <ul>
          <li>
            <strong>{company.legalName}</strong>
          </li>
          <li>{corporateOfficeLocation.query}</li>
          <li>
            Email: <a href={contact.emailHref}>{contact.email}</a>
          </li>
          <li>
            Phone: <a href={contact.phoneHref}>{contact.phone}</a>
          </li>
        </ul>
        <p>
          For anything relating to a specific booking or payment, please have your registered email and booking/plot
          details ready so we can locate your records quickly.
        </p>
      </>
    ),
  },
  {
    id: 'governing-law',
    heading: 'Governing law',
    body: (
      <p>
        This policy is governed by the laws of India. Subject to our Terms &amp; Conditions&rsquo;{' '}
        <Link to="/terms-conditions#dispute-resolution">&ldquo;Dispute resolution and jurisdiction&rdquo;</Link>{' '}
        clause, the courts at Karnal, Haryana shall have jurisdiction over any dispute arising from this policy.
      </p>
    ),
  },
];

export function PrivacyPolicyPage() {
  return (
    <LegalPageLayout
      eyebrow="Legal"
      title="Privacy Policy"
      intro="How Divine Vision Infratech collects, uses, stores and protects your personal data across this website, Divine Assist, and the customer and channel-partner dashboards."
      lastUpdated={LAST_UPDATED}
      sections={sections}
    />
  );
}
